---
- hosts: kubernetes-master-nodes
  become: yes
  tasks:
  - name: Pulling images for a Kubernetes  {{ k8s_version }} cluster
    command: kubeadm config images pull --kubernetes-version {{ k8s_version }} --image-repository {{ image_repository_gcr }}

  - name: Resetting kubeadm
    command: kubeadm reset -f
    register: output

  - name: Initializing Kubernetes cluster
    command: kubeadm init --apiserver-advertise-address {{ hostvars[ 'kubernetes-master' ].ansible_host }} --pod-network-cidr=10.244.0.0/16  --image-repository {{ image_repository_gcr }}
    register: output

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest=join_token
    become: no

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Copying flannel.yml
    template: 
      src: ./include/kube-flannel.yml.j2
      dest: /tmp/kube-flannel.yml
      mode: '0666'

  - name: Install Network Add-on
    command: kubectl apply -f /tmp/kube-flannel.yml

  - name: Dumping kube config into working space
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: ../kubeconfig
